import type { Metadata } from "next";
import "./globals.css";
import Navbar from "../components/Navbar"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
interface Children{
    children:React.ReactNode
}
export default function RootLayout({ children }:Children ) {
  return (
    <html
      lang="en"
    >
      <body className="min-h-full  flex flex-col">
         <Navbar/>
        <div className="">
        {children}
        </div>
        
        </body>
    </html>
  );
}
