import type { Metadata } from "next";
import "./globals.css";
import Navbar from "../components/Navbar/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
interface Children {
  children: React.ReactNode;
}
export default function RootLayout({ children }: Children) {
  return (
    <html lang="en">
      <body className="min-h-full flex flex-col gap-9">
        <Navbar />
        <div>{children}</div>
      </body>
    </html>
  );
}
