import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar"
// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
interface Children{
    children:React.ReactNode
}
export default function RootLayout({ children }:Children ) {
  return (
    <html
      lang="en"
    >
      <body className="min-h-full  flex flex-col">
         <Navbar/>
        <div className="">
        {children}
        </div>
        
        </body>
    </html>
  );
}
